# Generated by Django 4.2.5 on 2023-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
