# Generated by Django 4.2.5 on 2023-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patch_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='close_date',
            field=models.DateTimeField(),
        ),
    ]
