# Generated by Django 4.2.5 on 2023-10-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_patch_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
