# Generated by Django 4.2.5 on 2023-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_submissions_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='registeration_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='name',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='file_upload',
            field=models.FileField(upload_to=''),
        ),
    ]
