# Generated by Django 4.2.5 on 2023-10-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_registeration_id_submissions_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='file_upload',
            field=models.CharField(max_length=100),
        ),
    ]
