# Generated by Django 4.2.5 on 2023-10-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_submissions_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='verdict',
            field=models.BooleanField(default=False),
        ),
    ]
