# Generated by Django 4.2.5 on 2023-10-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_submissions_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='verdict',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
