# Generated by Django 4.2.5 on 2023-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_submissions_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='verdict',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Rejected'),
        ),
    ]
